"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$python \
dev
$character\
"""

right_format = """
$cmd_duration\
$status \
"""

[cmd_duration]
format = '[$duration]($style) '
min_time = 5_000

[fill]
symbol = ' '

[python]
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[status]
disabled = false
format = '[$status]($style) '

[time]
disabled = false
format = '[$time]($style)'

[directory]
truncation_length = 4

[git_branch]
format = '[$branch]($style) '
