# style name or JSON path (default "auto")
style: /home/ubuntu/.config/glamour/catppuccin-latte.json
# mouse support (TUI-mode only)
mouse: false
# use pager to display markdown
pager: true
# word-wrap at width
width: 100
# show all files, including hidden and ignored.
all: false
